package airflow

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/skaledata/cli/internal/api"
)

const (
	envAutoHeader = "# --- Auto-generated by skale airflow start (do not edit below this line) ---"
	envAutoFooter = "# --- End auto-generated ---"
)

// FetchAndWriteSecrets calls the dev-credentials API and writes
// credential files + .env config to the project directory.
// Returns the response for display purposes.
func FetchAndWriteSecrets(dir string, client *api.Client, appID string) (*api.DevCredentialsResponse, error) {
	fmt.Printf("  Fetching secrets backend config for %s...\n", appID)

	var resp api.DevCredentialsResponse
	if err := client.Post("/applications/"+appID+"/dev-credentials", nil, &resp); err != nil {
		return nil, fmt.Errorf("fetch dev credentials: %w", err)
	}

	skaleDir := filepath.Join(dir, ".skale")
	if err := os.MkdirAll(skaleDir, 0o755); err != nil {
		return nil, fmt.Errorf("create .skale/: %w", err)
	}

	// Build the auto-generated env vars
	var envLines []string

	// Secrets backend config
	backendKwargs, err := json.Marshal(resp.BackendKwargs)
	if err != nil {
		return nil, fmt.Errorf("marshal backend_kwargs: %w", err)
	}
	envLines = append(envLines,
		fmt.Sprintf("AIRFLOW__SECRETS__BACKEND=%s", resp.SecretsBackend),
		fmt.Sprintf("AIRFLOW__SECRETS__BACKEND_KWARGS=%s", string(backendKwargs)),
	)

	// Per-cloud credential files + env vars
	switch resp.CredentialType {
	case "gcp_service_account_key":
		if err := writeGCPCredentials(skaleDir, resp.Credentials, &envLines); err != nil {
			return nil, err
		}
	case "aws_sts":
		writeAWSCredentials(resp.Credentials, &envLines)
	case "azure_ad_token":
		if err := writeAzureCredentials(skaleDir, resp.Credentials, &envLines); err != nil {
			return nil, err
		}
	}

	// Write .env preserving user-defined vars
	envPath := filepath.Join(dir, ".env")
	if err := writeEnvFile(envPath, envLines); err != nil {
		return nil, fmt.Errorf("write .env: %w", err)
	}

	fmt.Println("  Wrote secrets config to .env")
	return &resp, nil
}

// RefreshSecrets re-mints credentials without restarting containers.
// For GCP/Azure (file-based), running containers pick up the new file.
// For AWS (env vars), a compose restart is needed (caller handles this).
func RefreshSecrets(dir string, client *api.Client, appID string) (*api.DevCredentialsResponse, error) {
	return FetchAndWriteSecrets(dir, client, appID)
}

func writeGCPCredentials(skaleDir string, creds map[string]any, envLines *[]string) error {
	// Write the service account key JSON to a credential file.
	// The Google SDK uses this natively — no refresh_token issues.
	keyJSON, ok := creds["key_json"].(map[string]any)
	if !ok {
		return fmt.Errorf("GCP credentials missing key_json")
	}

	data, err := json.MarshalIndent(keyJSON, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal GCP credentials: %w", err)
	}

	credPath := filepath.Join(skaleDir, "gcp-credentials.json")
	if err := os.WriteFile(credPath, data, 0o600); err != nil {
		return fmt.Errorf("write GCP credentials: %w", err)
	}
	fmt.Println("  Wrote .skale/gcp-credentials.json")

	*envLines = append(*envLines, "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json")
	return nil
}

func writeAWSCredentials(creds map[string]any, envLines *[]string) {
	accessKey, _ := creds["access_key_id"].(string)
	secretKey, _ := creds["secret_access_key"].(string)
	sessionToken, _ := creds["session_token"].(string)
	region, _ := creds["region"].(string)
	if region == "" {
		region = "us-east-1"
	}

	*envLines = append(*envLines,
		fmt.Sprintf("AWS_ACCESS_KEY_ID=%s", accessKey),
		fmt.Sprintf("AWS_SECRET_ACCESS_KEY=%s", secretKey),
		fmt.Sprintf("AWS_SESSION_TOKEN=%s", sessionToken),
		fmt.Sprintf("AWS_DEFAULT_REGION=%s", region),
	)
}

func writeAzureCredentials(skaleDir string, creds map[string]any, envLines *[]string) error {
	tenantID, _ := creds["tenant_id"].(string)
	clientID, _ := creds["client_id"].(string)
	token, _ := creds["token"].(string)

	// Write token to a file for the Azure SDK
	tokenJSON := map[string]string{
		"access_token": token,
	}
	data, err := json.MarshalIndent(tokenJSON, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal Azure token: %w", err)
	}

	tokenPath := filepath.Join(skaleDir, "azure-token.json")
	if err := os.WriteFile(tokenPath, data, 0o600); err != nil {
		return fmt.Errorf("write Azure token: %w", err)
	}
	fmt.Println("  Wrote .skale/azure-token.json")

	*envLines = append(*envLines,
		fmt.Sprintf("AZURE_CLIENT_ID=%s", clientID),
		fmt.Sprintf("AZURE_TENANT_ID=%s", tenantID),
		"AZURE_AUTHORITY_HOST=https://login.microsoftonline.com",
	)
	return nil
}

// writeEnvFile writes auto-generated env vars to .env while preserving
// any user-defined vars outside the auto-generated block.
func writeEnvFile(path string, autoLines []string) error {
	var userLines []string

	// Read existing file and extract user-defined lines
	existing, err := os.ReadFile(path)
	if err == nil {
		userLines = extractUserLines(string(existing))
	}

	// Build new file content
	var sb strings.Builder
	sb.WriteString(envAutoHeader + "\n")
	for _, line := range autoLines {
		sb.WriteString(line + "\n")
	}
	sb.WriteString(envAutoFooter + "\n")

	if len(userLines) > 0 {
		sb.WriteString("\n")
		for _, line := range userLines {
			sb.WriteString(line + "\n")
		}
	}

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// extractUserLines returns lines from the .env file that are outside
// the auto-generated block.
func extractUserLines(content string) []string {
	lines := strings.Split(content, "\n")
	var userLines []string
	inAutoBlock := false

	for _, line := range lines {
		if strings.TrimSpace(line) == strings.TrimSpace(envAutoHeader) {
			inAutoBlock = true
			continue
		}
		if strings.TrimSpace(line) == strings.TrimSpace(envAutoFooter) {
			inAutoBlock = false
			continue
		}
		if !inAutoBlock && strings.TrimSpace(line) != "" {
			userLines = append(userLines, line)
		}
	}
	return userLines
}
